=== CarlDeWitt/Tuks2022/IMY 210/assignments/Assignment 2/test/2/exam prep/nf.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://realbooks.cn/ns/1.0/nf"
xmlns:as="https://realbooks.cn/ns/1.0/nf">
<xs:import schemaLocation= "sample.xsd"></xs:import>
	<xs:element name="book">
        <xs:complexType>
            <xs:sequence>

            <!-- section1 -->
            <xs:element name="section">
                <xs:complexType>
                    <xs:sequence>

                        <!-- title -->
                        <xs:element name="title" type="as:limit255"/>

                        <!-- authors -->
                        <xs:element name="authors">
                            <xs:complexType>
                                <xs:sequence minOccurs="1" maxOccurs="unbounded">
                                    
                                    <!-- author -->
                                    <xs:element name="author" type="as:limit255"/>

                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <!-- publisher -->
                        <xs:element name="publisher">
                            <xs:complexType>
                                <xs:simpleContent>
                                    <xs:extension base="as:limit255">
                                        <xs:attribute name="year" type="as:years" />                                        
                                    </xs:extension>
                                </xs:simpleContent>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>
                </xs:complexType>   
            </xs:element>

            <!-- section2 -->
            <xs:element name="section">
                <xs:complexType>
                    <xs:sequence>

                        <!-- isbn -->
                        <xs:element name="isbn">
                            <xs:complexType>
                                <xs:sequence maxOccurs="3">

                                    <xs:element name="isbn" type="as:isbns"/>

                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                        <!-- notes -->
                        <xs:element name="notes" type="xs:string"/>

                        <!-- format -->
                        <xs:element name="format" type="as:limit255"/>

                        <!-- edition -->
                        <xs:element name="edition">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="0"/>
                                    <xs:maxInclusive value="20"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>

                        <!-- subjects -->
                        <xs:element name="subjects">
                            <xs:complexType>
                                <xs:sequence minOccurs="1" maxOccurs="unbounded">
                                    <xs:element name="subject" type="as:limit255"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>

                    </xs:sequence>
                </xs:complexType>

            </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

<xs:simpleType name="limit255">
    <xs:restriction base="xs:string">
        <xs:maxLength value="255"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="years">
    <xs:restriction base="xs:integer">
        <xs:minInclusive value="1900"/>
        <xs:maxInclusive value="2100"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="isbns">
    <xs:restriction base="xs:string">
        <xs:minLength value="10"/>
        <xs:maxLength value="13"/>
    </xs:restriction>
</xs:simpleType>
</xs:schema>

=== CarlDeWitt/Tuks2022/IMY 210/assignments/Assignment 2/test/2/exam prep/sample_nf.xml
<?xml version="1.0"?>
<nf:book xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="https://realbooks.cn/ns/1.0/nf nf.xsd"
xmlns:nf="https://realbooks.cn/ns/1.0/nf">
	<!-- <book> can contain only two <section> element-->
	<section>
		<!-- <section> can follow one of two formats -->
		<!-- All elements are required to appear in order formats: title, authors, publisher-->
		<title>Interaction design : beyond human-computer interaction</title>
			<!-- plain test, no longer than 255 character--> 
		<authors>	
			<!-- can hold infinite <author> elements, minimum being 1--> 
			<author>Helen Sharp</author>
			<!-- plain test, no longer than 255 character--> 
			<author>Yvonne Rogers</author>
			<author>Jenny Preece</author>
		</authors>
		<publisher year="2019">Wiley</publisher>
			<!-- plain test, no longer than 255 character--> 
	</section>
	<section>
		<!-- All elements are required to appear in order formats -->
		<isbn>
			<!-- <isbn> can either hold more <isbn> elements (maximum 3) or text -->
			<isbn>1119547253</isbn>
				<!-- <isbn> text can either be 10 or 13 characters-->
			<isbn>9781119547259</isbn>
		</isbn>
		<notes>
			<!-- plain text with no limitation on characters-->
			What's Inside? xvii 1 What is Interaction Design?
		</notes>
		<format>Print book</format>
			<!-- plain test, no longer than 255 character--> 
		<edition>5</edition>
			<!-- numberic value no larger than 20 -->
		<subjects>
			<!-- can hold infinite <subject> elements, minimum being 1--> 
			<subject>Human-computer interaction</subject>
				<!-- plain test, no longer than 255 character--> 
		</subjects>
	</section>
</nf:book>
