=== CarlDeWitt/Tuks2022/IMY 210/EO 3/u21444928_EO3/B DTD/dtd-xml.dtd
<!--Carl de Witt u21444928-->


<!-- game -->
<!ELEMENT game ((game, result) | ((rps) | (rpsls)))>
<!ATTLIST game icon CDATA #IMPLIED>
<!ELEMENT rps (rock|paper|scissors)>
<!ELEMENT rock EMPTY>
<!ELEMENT paper EMPTY>
<!ELEMENT scissors EMPTY>
<!ELEMENT lizard EMPTY>
<!ELEMENT spock EMPTY>
<!ATTLIST rps game_id CDATA #IMPLIED>
<!ELEMENT rpsls (rock|paper|scissors|lizard|spock)>
<!ATTLIST rpsls game_id CDATA #IMPLIED>
<!ELEMENT result (status)*>
<!ELEMENT status (#PCDATA)>
<!ATTLIST status game_id CDATA #REQUIRED>

<!ATTLIST rock beat CDATA #IMPLIED>
<!ATTLIST paper beat CDATA #IMPLIED>
<!ATTLIST scissors beat CDATA #IMPLIED>
<!ATTLIST lizard beat CDATA #IMPLIED>
<!ATTLIST spock beat CDATA #IMPLIED>

=== CarlDeWitt/Tuks2022/IMY 210/Examp Prep/EO 3/eo/B DTD/dtd-xml_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "dtd-xml.dtd">
<game icon="rpsls">
	<game>
		<rps game_id="GR01">
			<rock/>
		</rps>
		
		<rpsls game_id="GL01">
			<spock/>
		</rpsls>
		
		<rps game_id="GR02">
			<paper/>
		</rps>
	</game>
	
	<result>
		<status game_id="GR01">win</status>
		<status game_id="GL01">lose</status>
		<status game_id="GR02">lose</status>
	</result>
</game>
