=== CarlDeWitt/Tuks2022/IMY 210/assignments/A2 redo/f.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://realbooks.cn/ns/1.0/f" >
<xs:import schemaLocation= "sample.xsd"></xs:import>
	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
			<!--SCETION1-->
			 <xs:element name="section">
			 	<xs:complexType>
			 		<xs:sequence>
			 		
			 		<!--TITLE elemnt-->
			 			<xs:element name="title" type="LimitedString"/>
			 			
			 			
			 		<!--authors elemnt-->
			 		<xs:element name="authors">
			 			<xs:complexType>			 			
			 				<xs:sequence minOccurs="0" maxOccurs="10">
			 					<xs:element name="author" type="LimitedString"/>
			 					 
			 				</xs:sequence>
			 			</xs:complexType>
			 		</xs:element>
			 		
			 		<!--publisher elemnt-->
			 		<xs:element name="publisher">
			 			<xs:complexType>
			 				<xs:simpleContent>
			 					<xs:extension base="LimitedString">			 					
					 				<xs:attribute name="year">
					 					<xs:simpleType>
					 						<xs:restriction base="xs:integer">
					 							<xs:minInclusive value="1900"/>
												<xs:maxInclusive value="2100"/>
					 						</xs:restriction>
					 					</xs:simpleType>
					 				</xs:attribute>
					 			</xs:extension>
			 				</xs:simpleContent>
			 			</xs:complexType>
			 		</xs:element>
			 		</xs:sequence>
			 	</xs:complexType>
			 </xs:element>
			 
			 <!--SCETION2-->
			 <xs:element name="section">
			 	<xs:complexType>			 	
				 	<xs:sequence maxOccurs="unbounded">
				 		<xs:element name="rating">
				 			<xs:complexType>
			 					<xs:simpleContent>
			 						<xs:extension base="limitNumber">			 					
					 					<xs:attribute name="source" type="LimitedString">
					 					</xs:attribute>
					 			</xs:extension>
			 				</xs:simpleContent>
			 			</xs:complexType>
				 		</xs:element>
				 	</xs:sequence>
			 	</xs:complexType>
			 </xs:element>
			 
			 <!--SCETION3-->
			 <xs:element name="section">
			 	<xs:complexType>			 	
				 	<xs:sequence>
				 	
				 		<!--description-->
				 		<xs:element name="description">
				 			<xs:complexType>	
					 			<xs:sequence maxOccurs="unbounded">
					 			
						 			<!--pages-->
						 				<xs:element name="pages" type="xs:integer"/>
						 					
						 			<!--dimension-->
						 				<xs:element name="dimension" type="limitNumber">
							 
						 				</xs:element>
						 				
						 			<!--format-->
						 				<xs:element name="format" type="LimitedString">
				 				 	
						 				</xs:element>
						 			
						 			
						 				<xs:element name="edition" type="limitNumber">
	 												 
						 				</xs:element>
						 		
					 			</xs:sequence>
					 		</xs:complexType>	
				 		</xs:element>
				 		<!--genres-->
				 		<xs:element name="genres">
				 			<xs:complexType>				 			
				 				<xs:sequence maxOccurs="10">
					 				<!--genre-->
					 					<xs:element name="genre" type="LimitedString"/>			 					
	
				 				</xs:sequence>
				 			</xs:complexType>
				 		</xs:element>			 			
				 		
				 		<!--summary-->
				 		<xs:element name="summary" type="xs:string"/>
				 	</xs:sequence>
			 	</xs:complexType>
			 </xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

<!-- THisis the 50 chars restriction-->

=== CarlDeWitt/Tuks2022/IMY 210/assignments/A2/sample/sample_f.xml
<?xml version="1.0"?>
<f:book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="f.xsd" xmlns:f="www.f.com">
	<!-- <book> can contain up to three <section> element, all are optional-->
	<section>
		<!-- One of three formats all in sequence-->
			<!-- Format A: title, authors, publisher-->
			<!-- Format B: infinite amount of ratings-->
			<!-- Format C: description, genres, summary-->

		<title>Dressed to kill</title>
			<!-- plain test, no longer than 50 character--> 
		<authors>
		<!-- contain <author>, 10 at most-->
			<author>Charlotte Madison</author>
				<!-- plain test, no longer than 50 character--> 
		</authors>
		<publisher year="2010">London:Headline Review</publisher>
				<!-- plain test, no longer than 50 character--> 
				<!-- @year is a numeric value between 1900 - 2100-->
	</section>
	<section>
	<!-- contain infinite <rating> -->

		<rating source ="goodread">5</rating>
			<!-- numeric value, no larger than 10 -->
			<!-- @source is required and holds plain test, no longer than 50 character--> 
		<rating source ="imdb">4</rating>
		<rating source ="editor">3</rating>
	</section>
	<section>
		<description>
		<!-- element can appear in any order-->
			<pages>341</pages>
			<!-- numeric value -->
			<dimension>8</dimension>
			<!-- numeric value, no larger than 10 -->
			<format>Print book</format>
			<!-- plain test, no longer than 50 character--> 
			<edition>5</edition>
			<!-- numeric value, no larger than 10 -->
		</description>
		<genres>
			<!-- contain <genre>, 10 at most-->
			<genre>Erlebnisbericht</genre>
			<genre>Biography</genre>
				<!-- plain test, no longer than 50 character--> 
		</genres>
		<summary>
				<!-- plain text--> 
			 	'My fingers close around the trigger. I pause for a split second to think about the bullets I am about to spray across the ground. After today, I'll no longer be the new girl.' Captain Charlotte Madison is blonde, beautiful and flies Apache helicopters for a living. She has completed two tours of duty in Afghanistan and is currently fighting on the frontline in her third. Bird shows us what life is like for a girl in a resolutely male-dominated environment. But she isn't just a woman in a man's world, she's a woman women aspire to be --
				glamorous as well as brave, and beating the men at their own game. Only a tiny percentage of people can multi-task to the extreme level the aircraft demands, and most airmen who try to qualify as an Apache pilot fail. Full of the exciting, adrenaline-filled action that has made other military memoirs so successful, Bird is also unique. A highly intelligent and brilliant young woman, Charlotte is Britain's first female Apache pilot, and the first British female pilot to kill in an Apache. We have, quite simply, never seen the landscape of 21st-century frontline conflict from a perspective like hers before. Bird will appeal to anyone interested in current affairs, but it will also speak to a whole generation of young women who will relate to 27-year-old Charlotte in a way they never imagined possible.
		</summary>
	</section>
</book>
